name: Process Doc Pictures

on:
  push:
    branches:
      - main
    paths:
      - 'uploadDogs/**'
  workflow_dispatch: # Allow manual runs

jobs:
  process-uploadDogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Move, Rename, and Generate Thumbnails
        run: |
          mkdir -p dogs
          for file in uploadDogs/*.{jpg,jpeg,png}; do
            if [ -f "$file" ]; then
              # Generate a timestamp-based filename
              timestamp=$(date +%s%N | cut -b1-13) # Milliseconds timestamp
              extension="${file##*.}"
              new_filename="dogs/${timestamp}.${extension}"

              # Move file to dogs folder
              mv "$file" "$new_filename"

              # Generate thumbnail
              convert "$new_filename" -resize 200x200^ -gravity center -extent 200x200 \
                "dogs/${timestamp}_thumb.${extension}"

              echo "Processed $file → $new_filename and generated thumbnail."
            fi
          done

      - name: Generate photos.json
        run: |
          echo "[" > dogs/photos.json
          for thumb in dogs/*_thumb.{jpg,jpeg,png}; do
            full="${thumb/_thumb/}"
            echo "  {\"thumbnail\": \"$thumb\", \"full\": \"$full\"}," >> dogs/photos.json
          done
          sed -i '$ s/,$//' dogs/photos.json # Remove trailing comma
          echo "]" >> dogs/photos.json
          echo "Generated photos.json."

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Processed images: moved, renamed, generated thumbnails, and updated photos.json"
          branch: main
          file_pattern: "dogs/**"
