name: Process Uploaded Images

on:
  push:
    branches:
      - main
    paths:
      - 'uploadDogs/**'
  workflow_dispatch: # Allow manual runs

jobs:
  process-uploadDogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Move, Rename, and Generate Thumbnails
        run: |
          mkdir -p dogs
          for file in uploadDogs/*.{jpg,jpeg,png}; do
            if [ -f "$file" ]; then
              # Generate a timestamp-based filename
              timestamp=$(date +%s%N | cut -b1-13) # Milliseconds timestamp
              extension="${file##*.}"
              new_filename="dogs/${timestamp}.${extension}"
              thumb_filename="dogs/${timestamp}_thumb.${extension}"

              # Move file to dogs folder
              mv "$file" "$new_filename"

              # Generate thumbnail with natural aspect ratio
              convert "$new_filename" -resize "200x>" "$thumb_filename"

              echo "Processed $file → $new_filename and generated thumbnail $thumb_filename."
            fi
          done

      - name: Generate photos.json with Dimensions
        run: |
          echo "[" > dogs/photos.json
          for thumb in dogs/*_thumb.{jpg,jpeg,png}; do
            full="${thumb/_thumb/}"
            
            # Get dimensions for full image
            full_dims=$(identify -format "%w x %h" "$full")
            full_width=$(echo $full_dims | cut -d' ' -f1)
            full_height=$(echo $full_dims | cut -d' ' -f3)
            
            # Get dimensions for thumbnail
            thumb_dims=$(identify -format "%w x %h" "$thumb")
            thumb_width=$(echo $thumb_dims | cut -d' ' -f1)
            thumb_height=$(echo $thumb_dims | cut -d' ' -f3)
            
            # Append to JSON
            echo "  {" >> dogs/photos.json
            echo "    \"thumbnail\": \"$thumb\"," >> dogs/photos.json
            echo "    \"thumbnailWidth\": $thumb_width," >> dogs/photos.json
            echo "    \"thumbnailHeight\": $thumb_height," >> dogs/photos.json
            echo "    \"full\": \"$full\"," >> dogs/photos.json
            echo "    \"fullWidth\": $full_width," >> dogs/photos.json
            echo "    \"fullHeight\": $full_height" >> dogs/photos.json
            echo "  }," >> dogs/photos.json
          done
          sed -i '$ s/,$//' dogs/photos.json # Remove trailing comma
          echo "]" >> dogs/photos.json
          echo "Generated photos.json with dimensions."

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Processed images: added dimensions to photos.json"
          branch: main
          file_pattern: "."

