name: Process Images in uploadDogs

on:
  push:
    branches:
      - main
    paths:
      - 'uploadDogs/**' # Trigger only when files in uploadDogs change
  workflow_dispatch: # Allow manual runs

jobs:
  process-uploadDogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Move, Rename, and Generate Thumbnails
        run: |
          for file in uploadDogs/*.{jpg,jpeg,png}; do
            if [ -f "$file" ]; then
              filename=$(basename -- "$file")
              extension="${filename##*.}"
              base="${filename%.*}"
              
              # Generate a unique name with timestamp
              unique_name="${base}_$(date +%s)"
              
              # Rename the original file
              mv "$file" "uploadDogs/${unique_name}.${extension}"
              
              # Generate thumbnail using ImageMagick
              convert "uploadDogs/${unique_name}.${extension}" \
                -resize 200x200 "uploadDogs/${unique_name}_thumb.${extension}"
            fi
          done

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Processed new images in uploadDogs: renamed files and generated thumbnails"
          branch: main
          file_pattern: "uploadDogs/*"
