name: Process Images in uploadDogs

on:
  push:
    branches:
      - main
    paths:
      - 'uploadDogs/**' # Trigger only when files in uploadDogs change
  workflow_dispatch: # Allow manual runs

jobs:
  process-uploadDogs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js and Sharp
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install sharp

      - name: Move, Rename, and Generate Thumbnails
        run: |
          mkdir -p uploadDogs
          for file in uploadDogs/*.{jpg,jpeg,png}; do
            if [ -f "$file" ]; then
              filename=$(basename -- "$file")
              extension="${filename##*.}"
              base="${filename%.*}"
              
              # Generate a unique name with timestamp
              unique_name="${base}_$(date +%s)"
              
              # Rename the original file
              mv "$file" "uploadDogs/${unique_name}.${extension}"
              
              # Generate a thumbnail with Sharp
              npx sharp "uploadDogs/${unique_name}.${extension}" \
                --resize 200,200 \
                --to-file "uploadDogs/${unique_name}_thumb.${extension}"
            fi
          done

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Processed changes in uploadDogs: renamed files and generated thumbnails"
          branch: main
          file_pattern: "uploadDogs/*"
